config/routes.rb
Rails.application.routes.draw do

  	devise_for :users, controllers: {
  		omniauth_callbacks: "omniauth_callbacks"
	}
	root "bots#index"

  	post '/callback' => 'webhook#callback'
  	get '/push' => 'webhook#push'
  	get 'bots/select'
  	post 'bots/new'
 	resources :bots, :only => [:show, :index, :new, :create, :edit, :update, :destroy]
end

app/models/bot.rb
class Bot < ApplicationRecord	
	validates :text, presence: true
	validates :value, presence: true
end

app/controllers/bots_controller.rb
class BotsController < ApplicationController
  http_basic_authenticate_with :name => "mario", :password => "bot" if Rails.env == "production"
  before_action :authorize

    def authorize
      return redirect_to user_line_omniauth_authorize_path unless user_signed_in?
    end

	  # def show
   #  	@bot = Bot.find(params[:id])
   #    if @bot.uid == current_user.uid
   #    else
   #      redirect_to bots_path
   #      flash[:alert] = "無効なユーザ"
   #    end
 	 #  end

 	  def index
    	@bots = Bot.where(uid: current_user.uid)
  	end

    def select
      @apis = ApiList.all
      @bot = Bot.new
    end

  	def new
      @id = params[:api_id]
      if @id.blank?
        redirect_to bots_select_path
        flash[:alert] = "出力値を選択してください"
      else
    	 @bot = Bot.new
       @api = ApiList.find(@id.to_i)
      end
  	end

  	def create
      b = Bot.find_by(text: params[:bot][:text], uid: current_user.uid)
      @bot = Bot.new(params.require(:bot).permit(:text, :value, :api_id, :deadline, :keyword).merge(:uid => current_user.uid))
      if b.blank?
        if @bot.save
          redirect_to bots_path
          flash[:notice] = "Botを作成しました"
        else
          redirect_to bots_select_path
          flash[:alert] = "入力値または出力値が入力されていません"
        end
        
      else
        redirect_to bots_select_path
        flash[:alert] = "そのkeyはすでに存在します"
      end
	  end

  	def edit
    	@bot = Bot.find(params[:id])
      @api = ApiList.find(@bot.api_id.to_i)
      if @bot.uid == current_user.uid
      else
        redirect_to bots_path
        flash[:alert] = "無効なユーザ"
      end
  	end

  	def update
    	@bot = Bot.find(params[:id])
      if @bot.uid == current_user.uid
        b = Bot.find_by(text: params[:bot][:text], uid: current_user.uid)
        if b.blank? || @bot.text == params[:bot][:text]
          if @bot.update(params.require(:bot).permit(:text, :value, :deadline, :keyword))
            redirect_to bots_path
            flash[:notice] = "Botを編集しました"
          else
            redirect_to edit_bot_path
            flash[:alert] = "入力値または出力値が入力されていません"
          end
        else
          redirect_to edit_bot_path
          flash[:alert] = "そのkeyはすでに存在します"
        end
      else
        redirect_to bots_path
        flash[:alert] = "無効なユーザ"
      end
  	end

  	def destroy
    	@bot = Bot.find(params[:id])
      if @bot.uid == current_user.uid
         @bot.destroy
        redirect_to bots_path
        flash[:alert] = "Botを削除しました"
      else
        redirect_to bots_path
        flash[:alert] = "無効なユーザ"
      end
	  end
end

app/helpers/bots_helper.rb
module BotsHelper
end

app/views/bots/create.html.erb
<h1>Bots#create</h1>
<p>Find me in app/views/bots/create.html.erb</p>

app/views/bots/destroy.html.erb
<h1>Bots#destroy</h1>
<p>Find me in app/views/bots/destroy.html.erb</p>

app/views/bots/edit.html.erb
<h1>Bot 編集：<%= @api.api %></h1>
<hr>
<%= form_for @bot do |b| %>
  <% if @api.id.to_i == 1 %>
		<p>
			<br>
			<h3>位置情報</h3>
			<h3>　 +</h3>
			<p>入力値</p>
			<%= b.text_field :text , :class => "form-control my-form" %><br><br>
			<p>出力値</p><br>
			<label><%= b.radio_button :keyword, "G001" %>  居酒屋</label>
			<label>  <%= b.radio_button :keyword, "G002" %>  ダイニングバー</label>
			<label>  <%= b.radio_button :keyword, "G003" %>  創作料理</label>
			<label>  <%= b.radio_button :keyword, "G004" %>  和食</label>
			<label>  <%= b.radio_button :keyword, "G005" %>  洋食</label>
			<label>  <%= b.radio_button :keyword, "G006" %>  イタリアン・フレンチ</label>
			<label>  <%= b.radio_button :keyword, "G007" %>  中華</label>
			<label>  <%= b.radio_button :keyword, "G008" %>  焼肉・韓国料理</label>
			<label>  <%= b.radio_button :keyword, "G009" %>  アジアン</label>
			<label>  <%= b.radio_button :keyword, "G010" %>  各国料理</label>
			<label>  <%= b.radio_button :keyword, "G011" %>  カラオケ・パーティ</label>
			<label>  <%= b.radio_button :keyword, "G012" %>  バー</label>
			<label>  <%= b.radio_button :keyword, "G013" %>  ラーメン</label>
			<label>  <%= b.radio_button :keyword, "G016" %>  お好み焼・もんじゃ・鉄板焼き</label>
			<label>  <%= b.radio_button :keyword, "G014" %>  カフェ・スイーツ</label>
			<label>  <%= b.radio_button :keyword, "G015" %>  その他</label>
		</p>

		<p>
			<%= b.submit "変更する", :class => "btn btn-success" %>
		</p>

	<!-- textを選択した場合 -->
	<% elsif @api.id.to_i == 2 %>
		<p>
			<p>入力値</p>
			<%= b.text_field :text , :class => "form-control my-form" %><br><br>
			<p>出力値</p>
			<%= b.text_field :value , :class => "form-control my-form" %><br>
		</p>

		<p>
			<%= b.submit "変更する", :class => "btn btn-success" %>
		</p>

	<% elsif @api.id.to_i == 3 %>
		<p>
			<h3>期限</h3>
			<%= b.hidden_field :text %>
			<%= b.datetime_select :deadline %><br><br>
			<h3>期限</h3>
			<%= b.text_area :value , :class => "form-control my-form" %>
			<%= b.hidden_field :api_id, :value => @id %>
		</p>

		<p>
			<%= b.submit "変更する", :class => "btn btn-success" %>
		</p>
	<% elsif @api.id.to_i == 4 %>
	<p>
		<br>
		<p>入力値</p>
		<h3>位置情報</h3>
		<h3>　  +</h3><br>
		<%= b.text_field :text , :class => "form-control my-form" %><br><br>
		<p>出力値</p>
		<h3>位置情報周辺のおすすめグルメ</h3><br>
		<h4>検索フリーワード</h4><p>「,」区切りで最大10件まで条件に含めることができます</p>
		<%= b.text_field :keyword , :class => "form-control my-form" %>
		<%= b.hidden_field :value, :value => "位置情報周辺のおすすめグルメ" %><br>
		<%= b.hidden_field :api_id, :value => @id %>
	</p>

	<p>
		<%= b.submit "作成する", :class => "btn btn-success" %>
	</p>
	<% end %>
<% end %>

app/views/bots/index.html.erb
<h1>Bot 一覧</h1>
<table class="table">
	<tr class="active">
		<th>カテゴリ</th>
		<th>入力値</th>
		<th>出力値</th>
		<th>actions</th>
	</tr>
	<% @bots.each do |bot| %>
	<tr>
		<% if bot.api_id == 1 || bot.api_id == 4%>
			<th><%= ApiList.find(bot.api_id).api %></th>
			<th>位置情報 + <%= bot.text %></th>
			<th><%= bot.value %></th>
			<th><%= link_to "Edit", edit_bot_path(bot.id), :class => "btn btn-success"%> <%= link_to "Delete", bot_path(bot.id), method: :delete, data: {confirm: "削除してよろしいですか？"}, :class => "btn btn-danger"%></th>
		<% elsif bot.api_id == 2 %>
			<th><%= ApiList.find(bot.api_id).api %></th>
			<th><%= bot.text %></th>
			<th><%= bot.value %></th>
			<th><%= link_to "Edit", edit_bot_path(bot.id), :class => "btn btn-success"%> <%= link_to "Delete", bot_path(bot.id), method: :delete, data: {confirm: "削除してよろしいですか？"}, :class => "btn btn-danger"%></th>
		<% end %>
	</tr>
	<% end %>
</table>
<br>
<h1>Push通知 一覧</h1>
<table class="table">
	<tr class="active">
		<th>時間</th>
		<th>内容</th>
		<th>actions</th>
	</tr>
	<% @bots.each do |bot| %>
	<tr>
		<% if bot.api_id == 3 %>
			<th><%= bot.deadline %></th>
			<th><%= bot.value %></th>
			<th><%= link_to "Edit", edit_bot_path(bot.id), :class => "btn btn-success"%> <%= link_to "Delete", bot_path(bot.id), method: :delete, data: {confirm: "削除してよろしいですか？"}, :class => "btn btn-danger"%></th>
		<% end %>
	</tr>
	<% end %>
</table>

app/views/bots/new.html.erb
<%= form_for @bot do |b| %>
<h1>Bot 作成：<%= @api.api %></h1>
	<!-- ホットペッパーグルメを選択した場合 -->
	<% if @id.to_i == 1 %>
		<p>
			<br>
			<p>入力値</p>
			<h3>位置情報</h3>
			<h3>　  +</h3><br>
			<%= b.text_field :text , :class => "form-control my-form" %><br><br>
			<p>出力値</p>
			<h3>位置情報周辺のおすすめグルメ</h3><br>
			<h4>カテゴリ</h4>
			<label><%= b.radio_button :keyword, "G001" %>  居酒屋</label>
			<label>  <%= b.radio_button :keyword, "G002" %>  ダイニングバー</label>
			<label>  <%= b.radio_button :keyword, "G003" %>  創作料理</label>
			<label>  <%= b.radio_button :keyword, "G004" %>  和食</label>
			<label>  <%= b.radio_button :keyword, "G005" %>  洋食</label>
			<label>  <%= b.radio_button :keyword, "G006" %>  イタリアン・フレンチ</label>
			<label>  <%= b.radio_button :keyword, "G007" %>  中華</label>
			<label>  <%= b.radio_button :keyword, "G008" %>  焼肉・韓国料理</label>
			<label>  <%= b.radio_button :keyword, "G009" %>  アジアン</label>
			<label>  <%= b.radio_button :keyword, "G010" %>  各国料理</label>
			<label>  <%= b.radio_button :keyword, "G011" %>  カラオケ・パーティ</label>
			<label>  <%= b.radio_button :keyword, "G012" %>  バー</label>
			<label>  <%= b.radio_button :keyword, "G013" %>  ラーメン</label>
			<label>  <%= b.radio_button :keyword, "G016" %>  お好み焼・もんじゃ・鉄板焼き</label>
			<label>  <%= b.radio_button :keyword, "G014" %>  カフェ・スイーツ</label>
			<label>  <%= b.radio_button :keyword, "G015" %>  その他</label>
			<%= b.hidden_field :value, :value => "位置情報周辺のおすすめグルメ" %><br>
			<%= b.hidden_field :api_id, :value => @id %>
		</p>

		<p>
			<%= b.submit "作成する", :class => "btn btn-success" %>
		</p>

	<!-- textを選択した場合 -->
	<% elsif @id.to_i == 2 %>
		<p>
			<p>入力値</p>
			<%= b.text_field :text , :class => "form-control my-form" %><br><br>
			<p>出力値</p>
			<%= b.text_field :value , :class => "form-control my-form" %><br>
			<%= b.hidden_field :api_id, :value => @id %>
		</p>

		<p>
			<%= b.submit "作成する", :class => "btn btn-success" %>
		</p>

	<% elsif @id.to_i == 3 %>
		<p>
			<h3>期限</h3>
			<%= b.hidden_field :text, :value => (0...20).map{ (65 + rand(26)).chr }.join %>
			<%= b.datetime_select :deadline %><br><br>
			<h3>内容</h3>
			<%= b.text_area :value , :class => "form-control my-form" %>
			<%= b.hidden_field :api_id, :value => @id %>
		</p>

		<p>
			<%= b.submit "作成する", :class => "btn btn-success" %>
		</p>
	<% elsif @id.to_i == 4 %>
	<p>
		<br>
		<p>入力値</p>
		<h3>位置情報</h3>
		<h3>　  +</h3><br>
		<%= b.text_field :text , :class => "form-control my-form" %><br><br>
		<p>出力値</p>
		<h3>位置情報周辺のおすすめグルメ</h3><br>
		<h4>検索フリーワード</h4>
		<p>「,」区切りで最大10件まで条件に含めることができます。</p>
		<p>例：焼肉,食べ放題</p>
		<%= b.text_field :keyword , :class => "form-control my-form" %>
		<%= b.hidden_field :value, :value => "位置情報周辺のおすすめグルメ" %><br>
		<%= b.hidden_field :api_id, :value => @id %>
	</p>

	<p>
		<%= b.submit "作成する", :class => "btn btn-success" %>
	</p>
	<% end %>
<% end %>

app/views/bots/select.html.erb
<h1>出力値 選択</h1>
<%= form_tag bots_new_path do %>
<p>ホットペッパーよりぐるなびのがおすすめだよ</p>
<table class="table">
	<tr class="active">
		<th>出力値</th>
	</tr>
	<% @apis.each do |api| %>
		<tr>
			<th>
				<%= radio_button_tag :api_id, api.id %>  <%= api.api %>
			</th>
		</tr>
	<% end %>
</table>
<%= submit_tag "次へ", :class => "btn btn-success"%>
<% end %>

app/views/bots/show.html.erb
<h1>詳細</h1>
<hr>
<h4>入力値：<%= @bot.text %></h4>
<h4>出力値：<%= @bot.value %></h4>
<small><%= @bot.created_at %></small>
<hr>

<p>
    <a href="/mariobot/bots/<%= @bot.id %>/edit" class="btn btn-success">編集する</a>
</p>
<p>
	<%= link_to "削除する", bot_path(@bot.id), method: :delete, :class => "btn btn-danger"%>
</p>

app/views/bots/update.html.erb
<h1>Bots#update</h1>
<p>Find me in app/views/bots/update.html.erb</p>